// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdjsbfwbzdlatnammyjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkanNiZndiemRsYXRuYW1teWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDU4NTIsImV4cCI6MjA3MjEyMTg1Mn0.F4nqatBAF_oMvSLo2WPTs5lUhq9xTGWZlxC9cSufdcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});